# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mpsplan.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #ffffff;\n"
"        color: #000000;\n"
"        font-family: Arial, sans-serif;\n"
"        font-size: 14px;\n"
"    }\n"
"\n"
"    QPushButton {\n"
"        background-color: #f0f0f0;\n"
"        color: #000000;\n"
"        border: 1px solid #ccc;\n"
"        padding: 10px 20px;\n"
"        text-align: center;\n"
"        text-decoration: none;\n"
"        display: inline-block;\n"
"        font-size: 14px;\n"
"        margin: 4px 2px;\n"
"        cursor: pointer;\n"
"        border-radius: 8px;\n"
"    }\n"
"\n"
"    QPushButton:hover {\n"
"        background-color: #e0e0e0;\n"
"    }\n"
"\n"
"    QLabel {\n"
"        color: #000000;\n"
"        font-size: 14px;\n"
"        text-align: center;\n"
"    }\n"
"\n"
"    QLineEdit {\n"
"        background-color: #ffffff;\n"
"        color: #000000;\n"
"        border: 1px solid #ccc;\n"
"        padding: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QProgressBar {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 4px;\n"
"        text-align: center;\n"
"        color: #000000;\n"
"    }\n"
"\n"
"    QProgressBar::chunk {\n"
"        background-color: #e0e0e0;\n"
"    }\n"
"\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        color: #000000;\n"
"        border: 1px solid #ccc;\n"
"        padding: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QTextEdit {\n"
"        background-color: #ffffff;\n"
"        color: #000000;\n"
"        border: 1px solid #ccc;\n"
"        padding: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.fileUploadGroupBox = QtWidgets.QGroupBox(self.splitter)
        self.fileUploadGroupBox.setObjectName("fileUploadGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fileUploadGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uploadSalesForecastButton = QtWidgets.QPushButton(self.fileUploadGroupBox)
        self.uploadSalesForecastButton.setObjectName("uploadSalesForecastButton")
        self.verticalLayout_2.addWidget(self.uploadSalesForecastButton)
        self.salesForecastStatusLabel = QtWidgets.QLabel(self.fileUploadGroupBox)
        self.salesForecastStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.salesForecastStatusLabel.setObjectName("salesForecastStatusLabel")
        self.verticalLayout_2.addWidget(self.salesForecastStatusLabel)
        self.uploadInventoryButton = QtWidgets.QPushButton(self.fileUploadGroupBox)
        self.uploadInventoryButton.setObjectName("uploadInventoryButton")
        self.verticalLayout_2.addWidget(self.uploadInventoryButton)
        self.inventoryStatusLabel = QtWidgets.QLabel(self.fileUploadGroupBox)
        self.inventoryStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inventoryStatusLabel.setObjectName("inventoryStatusLabel")
        self.verticalLayout_2.addWidget(self.inventoryStatusLabel)
        self.uploadProductionOrdersButton = QtWidgets.QPushButton(self.fileUploadGroupBox)
        self.uploadProductionOrdersButton.setObjectName("uploadProductionOrdersButton")
        self.verticalLayout_2.addWidget(self.uploadProductionOrdersButton)
        self.productionOrdersStatusLabel = QtWidgets.QLabel(self.fileUploadGroupBox)
        self.productionOrdersStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.productionOrdersStatusLabel.setObjectName("productionOrdersStatusLabel")
        self.verticalLayout_2.addWidget(self.productionOrdersStatusLabel)
        self.uploadSafetyStockButton = QtWidgets.QPushButton(self.fileUploadGroupBox)
        self.uploadSafetyStockButton.setObjectName("uploadSafetyStockButton")
        self.verticalLayout_2.addWidget(self.uploadSafetyStockButton)
        self.safetyStockStatusLabel = QtWidgets.QLabel(self.fileUploadGroupBox)
        self.safetyStockStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.safetyStockStatusLabel.setObjectName("safetyStockStatusLabel")
        self.verticalLayout_2.addWidget(self.safetyStockStatusLabel)
        self.operationGroupBox = QtWidgets.QGroupBox(self.splitter)
        self.operationGroupBox.setObjectName("operationGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.operationGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.runButton = QtWidgets.QPushButton(self.operationGroupBox)
        self.runButton.setObjectName("runButton")
        self.verticalLayout_3.addWidget(self.runButton)
        self.exportButton = QtWidgets.QPushButton(self.operationGroupBox)
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout_3.addWidget(self.exportButton)
        self.logGroupBox = QtWidgets.QGroupBox(self.splitter)
        self.logGroupBox.setObjectName("logGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.logGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.logTextEdit = QtWidgets.QTextEdit(self.logGroupBox)
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setStyleSheet("\n"
"            QTextEdit {\n"
"                background-color: #ffffff;\n"
"                color: #000000;\n"
"                border: 1px solid #ccc;\n"
"                padding: 5px;\n"
"                border-radius: 4px;\n"
"            }\n"
"           ")
        self.logTextEdit.setObjectName("logTextEdit")
        self.verticalLayout_4.addWidget(self.logTextEdit)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "排产计划工具"))
        self.fileUploadGroupBox.setTitle(_translate("MainWindow", "文件上传"))
        self.uploadSalesForecastButton.setText(_translate("MainWindow", "上传销售预测文件"))
        self.salesForecastStatusLabel.setText(_translate("MainWindow", "未上传"))
        self.uploadInventoryButton.setText(_translate("MainWindow", "上传现存量查询文件"))
        self.inventoryStatusLabel.setText(_translate("MainWindow", "未上传"))
        self.uploadProductionOrdersButton.setText(_translate("MainWindow", "上传生产订单列表文件"))
        self.productionOrdersStatusLabel.setText(_translate("MainWindow", "未上传"))
        self.uploadSafetyStockButton.setText(_translate("MainWindow", "上传安全库存文件"))
        self.safetyStockStatusLabel.setText(_translate("MainWindow", "未上传"))
        self.operationGroupBox.setTitle(_translate("MainWindow", "操作"))
        self.runButton.setText(_translate("MainWindow", "执行操作"))
        self.exportButton.setText(_translate("MainWindow", "导出结果"))
        self.logGroupBox.setTitle(_translate("MainWindow", "日志"))
