# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #ffffff;\n"
"        color: #000000;\n"
"        font-family: Arial, sans-serif;\n"
"        font-size: 14px;\n"
"    }\n"
"\n"
"    QPushButton {\n"
"        background-color: #f0f0f0;\n"
"        color: #000000;\n"
"        border: 1px solid #ccc;\n"
"        padding: 10px 20px;\n"
"        text-align: center;\n"
"        text-decoration: none;\n"
"        display: inline-block;\n"
"        font-size: 14px;\n"
"        margin: 4px 2px;\n"
"        cursor: pointer;\n"
"        border-radius: 8px;\n"
"    }\n"
"\n"
"    QPushButton:hover {\n"
"        background-color: #e0e0e0;\n"
"    }\n"
"\n"
"    QLabel {\n"
"        color: #000000;\n"
"        font-size: 14px;\n"
"    }\n"
"\n"
"    QLineEdit {\n"
"        background-color: #ffffff;\n"
"        color: #000000;\n"
"        border: 1px solid #ccc;\n"
"        padding: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QProgressBar {\n"
"        background-color: #ffffff;\n"
"        border: 1px solid #ccc;\n"
"        border-radius: 4px;\n"
"        text-align: center;\n"
"        color: #000000;\n"
"    }\n"
"\n"
"    QProgressBar::chunk {\n"
"        background-color: #e0e0e0;\n"
"    }\n"
"\n"
"    QTableWidget {\n"
"        background-color: #ffffff;\n"
"        color: #000000;\n"
"        border: 1px solid #ccc;\n"
"        padding: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QTextEdit {\n"
"        background-color: #ffffff;\n"
"        color: #000000;\n"
"        border: 1px solid #ccc;\n"
"        padding: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QMenuBar {\n"
"        background-color: #f0f0f0;\n"
"        color: #000000;\n"
"    }\n"
"\n"
"    QMenu {\n"
"        background-color: #f0f0f0;\n"
"        color: #000000;\n"
"    }\n"
"\n"
"    QMenu::item {\n"
"        background-color: transparent;\n"
"        color: #000000;\n"
"    }\n"
"\n"
"    QMenu::item:selected {\n"
"        background-color: #e0e0e0;\n"
"        color: #000000;\n"
"    }\n"
"\n"
"    QMenu::item:hover {\n"
"        background-color: #d0d0d0;\n"
"        color: #000000;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.logTextEdit.setStyleSheet("\n"
"        QTextEdit {\n"
"            background-color: #ffffff;\n"
"            color: #000000;\n"
"            border: 1px solid #ccc;\n"
"            padding: 5px;\n"
"            border-radius: 4px;\n"
"        }\n"
"       ")
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setObjectName("logTextEdit")
        self.verticalLayout.addWidget(self.logTextEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFunctions = QtWidgets.QMenu(self.menubar)
        self.menuFunctions.setObjectName("menuFunctions")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPre_Scheduling = QtWidgets.QAction(MainWindow)
        self.actionPre_Scheduling.setObjectName("actionPre_Scheduling")
        self.actionCreate_Production_Material_Details = QtWidgets.QAction(MainWindow)
        self.actionCreate_Production_Material_Details.setObjectName("actionCreate_Production_Material_Details")
        self.actionCreate_Next_Month_Production_Plan = QtWidgets.QAction(MainWindow)
        self.actionCreate_Next_Month_Production_Plan.setObjectName("actionCreate_Next_Month_Production_Plan")
        self.actionCreate_Next_Month_Material_Procurement_Plan = QtWidgets.QAction(MainWindow)
        self.actionCreate_Next_Month_Material_Procurement_Plan.setObjectName("actionCreate_Next_Month_Material_Procurement_Plan")
        self.actionConfirm_In_Transit_Material_Arrival_Status = QtWidgets.QAction(MainWindow)
        self.actionConfirm_In_Transit_Material_Arrival_Status.setObjectName("actionConfirm_In_Transit_Material_Arrival_Status")
        self.actionHelp_Document = QtWidgets.QAction(MainWindow)
        self.actionHelp_Document.setObjectName("actionHelp_Document")
        self.actionFAQ = QtWidgets.QAction(MainWindow)
        self.actionFAQ.setObjectName("actionFAQ")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFunctions.addAction(self.actionPre_Scheduling)
        self.menuFunctions.addAction(self.actionCreate_Production_Material_Details)
        self.menuFunctions.addAction(self.actionCreate_Next_Month_Production_Plan)
        self.menuFunctions.addAction(self.actionCreate_Next_Month_Material_Procurement_Plan)
        self.menuFunctions.addAction(self.actionConfirm_In_Transit_Material_Arrival_Status)
        self.menuHelp.addAction(self.actionHelp_Document)
        self.menuHelp.addAction(self.actionFAQ)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFunctions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "排产计划工具"))
        self.menuFunctions.setTitle(_translate("MainWindow", "功能"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.actionPre_Scheduling.setText(_translate("MainWindow", "预排产计划"))
        self.actionCreate_Production_Material_Details.setText(_translate("MainWindow", "制作生产用料明细"))
        self.actionCreate_Next_Month_Production_Plan.setText(_translate("MainWindow", "制作次月生产计划"))
        self.actionCreate_Next_Month_Material_Procurement_Plan.setText(_translate("MainWindow", "制作次月物料采购计划"))
        self.actionConfirm_In_Transit_Material_Arrival_Status.setText(_translate("MainWindow", "确认在途订单物料到货状况"))
        self.actionHelp_Document.setText(_translate("MainWindow", "帮助文档"))
        self.actionFAQ.setText(_translate("MainWindow", "常见问题"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
