from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        
        self.fileUploadGroupBox = QtWidgets.QGroupBox(self.splitter)
        self.fileUploadGroupBox.setObjectName("fileUploadGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fileUploadGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uploadSalesForecastButton = QtWidgets.QPushButton(self.fileUploadGroupBox)
        self.uploadSalesForecastButton.setObjectName("uploadSalesForecastButton")
        self.verticalLayout_2.addWidget(self.uploadSalesForecastButton)
        self.salesForecastStatusLabel = QtWidgets.QLabel(self.fileUploadGroupBox)
        self.salesForecastStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.salesForecastStatusLabel.setObjectName("salesForecastStatusLabel")
        self.verticalLayout_2.addWidget(self.salesForecastStatusLabel)
        self.uploadInventoryButton = QtWidgets.QPushButton(self.fileUploadGroupBox)
        self.uploadInventoryButton.setObjectName("uploadInventoryButton")
        self.verticalLayout_2.addWidget(self.uploadInventoryButton)
        self.inventoryStatusLabel = QtWidgets.QLabel(self.fileUploadGroupBox)
        self.inventoryStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inventoryStatusLabel.setObjectName("inventoryStatusLabel")
        self.verticalLayout_2.addWidget(self.inventoryStatusLabel)
        self.uploadProductionOrdersButton = QtWidgets.QPushButton(self.fileUploadGroupBox)
        self.uploadProductionOrdersButton.setObjectName("uploadProductionOrdersButton")
        self.verticalLayout_2.addWidget(self.uploadProductionOrdersButton)
        self.productionOrdersStatusLabel = QtWidgets.QLabel(self.fileUploadGroupBox)
        self.productionOrdersStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.productionOrdersStatusLabel.setObjectName("productionOrdersStatusLabel")
        self.verticalLayout_2.addWidget(self.productionOrdersStatusLabel)
        self.uploadSafetyStockButton = QtWidgets.QPushButton(self.fileUploadGroupBox)
        self.uploadSafetyStockButton.setObjectName("uploadSafetyStockButton")
        self.verticalLayout_2.addWidget(self.uploadSafetyStockButton)
        self.safetyStockStatusLabel = QtWidgets.QLabel(self.fileUploadGroupBox)
        self.safetyStockStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.safetyStockStatusLabel.setObjectName("safetyStockStatusLabel")
        self.verticalLayout_2.addWidget(self.safetyStockStatusLabel)

        self.configGroupBox = QtWidgets.QGroupBox(self.splitter)
        self.configGroupBox.setObjectName("configGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.configGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        
        self.month1Layout = QtWidgets.QHBoxLayout()
        self.month1HoursLabel = QtWidgets.QLabel(self.configGroupBox)
        self.month1HoursLabel.setObjectName("month1HoursLabel")
        self.month1Layout.addWidget(self.month1HoursLabel)
        self.month1HoursInput = QtWidgets.QLineEdit(self.configGroupBox)
        self.month1HoursInput.setObjectName("month1HoursInput")
        self.month1Layout.addWidget(self.month1HoursInput)
        self.month1MinProductionLabel = QtWidgets.QLabel(self.configGroupBox)
        self.month1MinProductionLabel.setObjectName("month1MinProductionLabel")
        self.month1Layout.addWidget(self.month1MinProductionLabel)
        self.month1MinProductionInput = QtWidgets.QLineEdit(self.configGroupBox)
        self.month1MinProductionInput.setObjectName("month1MinProductionInput")
        self.month1Layout.addWidget(self.month1MinProductionInput)
        self.verticalLayout_5.addLayout(self.month1Layout)

        self.month2Layout = QtWidgets.QHBoxLayout()
        self.month2HoursLabel = QtWidgets.QLabel(self.configGroupBox)
        self.month2HoursLabel.setObjectName("month2HoursLabel")
        self.month2Layout.addWidget(self.month2HoursLabel)
        self.month2HoursInput = QtWidgets.QLineEdit(self.configGroupBox)
        self.month2HoursInput.setObjectName("month2HoursInput")
        self.month2Layout.addWidget(self.month2HoursInput)
        self.month2MinProductionLabel = QtWidgets.QLabel(self.configGroupBox)
        self.month2MinProductionLabel.setObjectName("month2MinProductionLabel")
        self.month2Layout.addWidget(self.month2MinProductionLabel)
        self.month2MinProductionInput = QtWidgets.QLineEdit(self.configGroupBox)
        self.month2MinProductionInput.setObjectName("month2MinProductionInput")
        self.month2Layout.addWidget(self.month2MinProductionInput)
        self.verticalLayout_5.addLayout(self.month2Layout)

        self.month3Layout = QtWidgets.QHBoxLayout()
        self.month3HoursLabel = QtWidgets.QLabel(self.configGroupBox)
        self.month3HoursLabel.setObjectName("month3HoursLabel")
        self.month3Layout.addWidget(self.month3HoursLabel)
        self.month3HoursInput = QtWidgets.QLineEdit(self.configGroupBox)
        self.month3HoursInput.setObjectName("month3HoursInput")
        self.month3Layout.addWidget(self.month3HoursInput)
        self.month3MinProductionLabel = QtWidgets.QLabel(self.configGroupBox)
        self.month3MinProductionLabel.setObjectName("month3MinProductionLabel")
        self.month3Layout.addWidget(self.month3MinProductionLabel)
        self.month3MinProductionInput = QtWidgets.QLineEdit(self.configGroupBox)
        self.month3MinProductionInput.setObjectName("month3MinProductionInput")
        self.month3Layout.addWidget(self.month3MinProductionInput)
        self.verticalLayout_5.addLayout(self.month3Layout)

        self.month4Layout = QtWidgets.QHBoxLayout()
        self.month4HoursLabel = QtWidgets.QLabel(self.configGroupBox)
        self.month4HoursLabel.setObjectName("month4HoursLabel")
        self.month4Layout.addWidget(self.month4HoursLabel)
        self.month4HoursInput = QtWidgets.QLineEdit(self.configGroupBox)
        self.month4HoursInput.setObjectName("month4HoursInput")
        self.month4Layout.addWidget(self.month4HoursInput)
        self.month4MinProductionLabel = QtWidgets.QLabel(self.configGroupBox)
        self.month4MinProductionLabel.setObjectName("month4MinProductionLabel")
        self.month4Layout.addWidget(self.month4MinProductionLabel)
        self.month4MinProductionInput = QtWidgets.QLineEdit(self.configGroupBox)
        self.month4MinProductionInput.setObjectName("month4MinProductionInput")
        self.month4Layout.addWidget(self.month4MinProductionInput)
        self.verticalLayout_5.addLayout(self.month4Layout)

        self.operationGroupBox = QtWidgets.QGroupBox(self.splitter)
        self.operationGroupBox.setObjectName("operationGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.operationGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.runButton = QtWidgets.QPushButton(self.operationGroupBox)
        self.runButton.setObjectName("runButton")
        self.verticalLayout_3.addWidget(self.runButton)
        self.exportButton = QtWidgets.QPushButton(self.operationGroupBox)
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout_3.addWidget(self.exportButton)
        
        self.logGroupBox = QtWidgets.QGroupBox(self.splitter)
        self.logGroupBox.setObjectName("logGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.logGroupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.logTextEdit = QtWidgets.QTextEdit(self.logGroupBox)
        self.logTextEdit.setReadOnly(True)

        self.logTextEdit.setObjectName("logTextEdit")
        self.verticalLayout_4.addWidget(self.logTextEdit)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "排产计划工具"))
        self.fileUploadGroupBox.setTitle(_translate("MainWindow", "文件上传"))
        self.uploadSalesForecastButton.setText(_translate("MainWindow", "上传销售预测文件"))
        self.salesForecastStatusLabel.setText(_translate("MainWindow", "未上传"))
        self.uploadInventoryButton.setText(_translate("MainWindow", "上传现存量查询文件"))
        self.inventoryStatusLabel.setText(_translate("MainWindow", "未上传"))
        self.uploadProductionOrdersButton.setText(_translate("MainWindow", "上传生产订单列表文件"))
        self.productionOrdersStatusLabel.setText(_translate("MainWindow", "未上传"))
        self.uploadSafetyStockButton.setText(_translate("MainWindow", "上传安全库存文件"))
        self.safetyStockStatusLabel.setText(_translate("MainWindow", "未上传"))
        self.configGroupBox.setTitle(_translate("MainWindow", "配置"))
        self.operationGroupBox.setTitle(_translate("MainWindow", "操作"))
        self.runButton.setText(_translate("MainWindow", "执行操作"))
        self.exportButton.setText(_translate("MainWindow", "导出结果"))
        self.logGroupBox.setTitle(_translate("MainWindow", "日志"))

        # 设置工时输入框和月最低生产量输入框的标签
        self.month1HoursLabel.setText(_translate("MainWindow", "第一个月工时:"))
        self.month1MinProductionLabel.setText(_translate("MainWindow", "最低生产量:"))
        self.month2HoursLabel.setText(_translate("MainWindow", "第二个月工时:"))
        self.month2MinProductionLabel.setText(_translate("MainWindow", "最低生产量:"))
        self.month3HoursLabel.setText(_translate("MainWindow", "第三个月工时:"))
        self.month3MinProductionLabel.setText(_translate("MainWindow", "最低生产量:"))
        self.month4HoursLabel.setText(_translate("MainWindow", "第四个月工时:"))
        self.month4MinProductionLabel.setText(_translate("MainWindow", "最低生产量:"))
